export const LOGIN = 'LOGIN/SUCCESS';
export const LOGIN_LOADING = 'LOGIN/LOADING';
export const REGISTER_USER = 'REGISTER_USER/SUCCESS';
export const LOGIN_FAIL = 'LOGIN/FAIL';
export const REGISTER_USER_FAIL = 'REGISTER_USER/FAIL';
export const REGISTER_USER_LOADING = 'REGISTER_USER/LOADING';

export const GET_USER = 'GET_USER/SUCCESS';
export const GET_USER_LOADING = 'GET_USER/LOADING';
export const GET_USER_FAIL = 'GET_USER/FAIL';

export const GET_ONLINE_FRIENDS = 'GET_ONLINE_FRIENDS/SUCCESS';

export const RECEIVED_NEW_MESSAGE = 'RECEIVED_NEW_MESSAGE/SUCCESS';
export const SENT_NEW_MESSAGE = 'SENT_NEW_MESSAGE/SUCCESS';
